# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='currency',
            field=models.CharField(db_index=True, default='USD', max_length=3),
        ),
    ]
